apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: fastapi-backend:latest  # мы позже загрузим его в кластер
          imagePullPolicy: Never         # использовать локальный образ
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URL
              value: "mongodb://mongo:27017"
            - name: APP_ROOT_PATH
              value: "/api"
