# ============================================
# Makefile for Full-Stack Kubernetes Project
# ============================================

include make/argo.mk
include make/docker.mk
include make/git.mk
include make/helm.mk
include make/ingress.mk
include make/k8s.mk
include make/monitoring.mk

# --------------------------------------------
# Help Menu
# --------------------------------------------

help:
	@echo ""
	@echo "ArgoCD Commands:"
	@echo "  make init-namespaces         - Create namespaces used by ArgoCD apps"
	@echo "  make check-argocd            - Check if ArgoCD CLI is installed"
	@echo "  make argo-apply ENV=dev      - Apply ArgoCD app manifest for environment"
	@echo "  make argo-delete ENV=dev     - Delete ArgoCD app manifest"
	@echo "  make argo-status             - Show ArgoCD application status"
	@echo "  make argo-sync               - Sync ArgoCD application (requires CLI)"
	@echo "  make argo-login              - Login to ArgoCD with initial password"
	@echo "  make argo-password           - Show initial admin password"
	@echo "  make argo-help               - Show this help menu"
	@echo ""
	@echo "Docker Compose Commands:"
	@echo "  make up              - Start all services with build"
	@echo "  make down            - Stop all running services"
	@echo "  make build           - Build Docker images only"
	@echo "  make restart         - Rebuild and restart all services"
	@echo "  make logs            - Tail logs from all services"
	@echo "  make frontend        - Start only the frontend service"
	@echo "  make backend         - Start only the backend service"
	@echo "  make docker-help     - Show this help message"
	@echo ""
	@echo "Available Git rollback commands:"
	@echo "  make rollback-one-commit       - Checkout previous commit (HEAD^)"
	@echo "  make rollback-main             - Return to 'main' branch"
	@echo "  make git-back N=<number>       - Checkout N commits back from HEAD"
	@echo "  make git-help                  - Show this help message"
	@echo ""
	@echo "== Helm Commands =="
	@echo "  make helm-install           - Install or upgrade the Helm release"
	@echo "  make helm-upgrade ENV=dev   - Upgrade Helm release for specific environment"
	@echo "  make helm-lint              - Lint the Helm chart"
	@echo "  make helm-uninstall ENV=dev - Uninstall the Helm release"
	@echo "  make helm-status ENV=dev    - Show Helm release status"
	@echo "  make helm-rollback ENV=dev  - Roll back Helm release"
	@echo "  make helm-upgrade-lint ENV=dev - Lint and upgrade"
	@echo "  make helm-reset ENV=dev     - Reset Helm release and run tests"
	@echo "  make helm-test ENV=dev      - Run Helm test suite"
	@echo "  make helm-monitoring        - Deploy monitoring stack"
	@echo "  make helm-help              - Show this help message"
	@echo ""
	@echo "Ingress Commands:"
	@echo "  make ingress-install          - Install NGINX ingress controller"
	@echo "  make ingress-uninstall        - Uninstall ingress controller and delete namespace"
	@echo "  make ingress-status           - Show status of ingress pods"
	@echo "  make ingress-proxy            - Port forward ingress to localhost:8080"
	@echo "  make ingress-check            - Run basic ingress curl tests"
	@echo "  make check-ingress            - Ensure ingress controller is installed"
	@echo "  make ingress-help             - Show this help message"
	@echo ""
	@echo "Kubernetes Commands:"
	@echo "  make apply-mongo          - Apply MongoDB resources"
	@echo "  make apply-backend        - Apply backend resources"
	@echo "  make apply-frontend       - Apply frontend resources"
	@echo "  make apply-ingress        - Apply ingress resources"
	@echo "  make apply-all            - Apply all resources"
	@echo "  make delete-all           - Delete all applied resources"
	@echo "  make restart-all          - Restart all deployments"
	@echo "  make k8s-status           - Show status of all k8s resources"
	@echo "  make check-health         - Check health of all pods in 'dev' namespace"
	@echo "  make logs-backend         - Tail logs from backend pods"
	@echo "  make logs-frontend        - Tail logs from frontend pods"
	@echo "  make rebuild-backend      - Rebuild and restart backend container"
	@echo "  make rebuild-frontend     - Rebuild and restart frontend container"
	@echo "  make rebuild-all          - Rebuild both frontend and backend"
	@echo "  k8s-help				   - Show this help menu"
	@echo ""
	@echo "Available ArgoCD-related commands:"
	@echo "  make dev-tools             - Start ArgoCD, Prometheus, Grafana and Dashboard tools"
	@echo "  make argo-ingress          - Apply ArgoCD Ingress resource"
	@echo "  make argo-password         - Show initial ArgoCD admin password (PowerShell only)"
	@echo "  make prometheus-proxy      - Port-forward to Prometheus UI (localhost:9090)"
	@echo "  make grafana-proxy         - Port-forward to Grafana UI (localhost:3000)"
	@echo "  make grafana-password      - Show Grafana admin password"
	@echo "  make dashboard-proxy       - Start Kubernetes proxy (Dashboard access)"
	@echo "  make dashboard-token       - Print login token for Kubernetes dashboard"
	@echo ""