apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.backend.containerPort }}
          command:
            - uvicorn
            - app.main:app
            - --host
            - '0.0.0.0'
            - --port
            - '{{ .Values.backend.containerPort }}'
            - --reload
