apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mongo.pvcName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongo.storage }}
