apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fullstack.fullname" . }}-secret
type: Opaque
stringData:
  MONGO_URI: {{ .Values.secret.mongoUri | quote }}
  JWT_SECRET: {{ .Values.secret.jwtSecret | quote }}
