backend:
  fullnameOverride: backend
  image: fastapi-backend:latest
  replicaCount: 1
  containerPort: 8000

frontend:
  fullnameOverride: frontend
  image: nextjs-frontend:latest
  replicaCount: 1
  containerPort: 3000
  debugPort: 9229

mongo:
  fullnameOverride: mongo
  image: mongo:6
  containerPort: 27017
  pvcName: mongo-pvc
  storage: 1Gi

secret:
  mongoUri: "mongodb://mongo:27017"
  jwtSecret: "super-secret-dev-jwt-key"
  
ingress:
  enabled: true
  className: nginx
  host: localhost
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  paths:
    - path: /api(/|$)(.*)
      pathType: ImplementationSpecific
      serviceName: backend
      servicePort: 8000
    - path: /
      pathType: ImplementationSpecific
      serviceName: frontend
      servicePort: 3000
