global:
  environment: prod
frontend:
  image: nextjs-frontend:prod
  replicaCount: 3
backend:
  image: fastapi-backend:prod
  replicaCount: 3
mongo:
  pvcName: mongo-pvc-prod
  image: mongo:6
  storage: 4Gi
  containerPort: 27017
ingress:
  host: prod.localhost
secret:
  mongoUri: "mongodb://mongo:27017"
  jwtSecret: "super-secret-dev-jwt-key"

