global:
  environment: staging
frontend:
  image: nextjs-frontend:staging
  replicaCount: 2
backend:
  image: fastapi-backend:staging
  replicaCount: 2
mongo:
  pvcName: mongo-pvc-staging
  image: mongo:6
  storage: 2Gi
  containerPort: 27017
ingress:
  host: staging.localhost
secret:
  mongoUri: "mongodb://mongo:27017"
  jwtSecret: "super-secret-dev-jwt-key"

